services:
#    gm_user.example:
#        class: GM\UserBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

  app.form.registration:
      class: GM\UserBundle\Form\RegistrationFormType
      tags:
          - { name: form.type }