security:

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
        



    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        GM\UserBundle\Entity\User: sha512

    role_hierarchy:
        ROLE_ADMIN:       [ROLE_USER,ROLE_AUTEUR, ROLE_MODERATEUR]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        main:
            entity:
                class:    GM\UserBundle\Entity\User
                property: username
        main:
            id: fos_user.user_provider.username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main_login:
       
            pattern:   ^/login$
            anonymous: true 

        main_signup:
       
            pattern:   ^/signup$
            anonymous: true 

        main:
            pattern:   ^/
            anonymous: true
            provider:  main 
            form_login:
                login_path: fos_user_security_login
                check_path: fos_user_security_check
            logout:
                path:       fos_user_security_logout
                target:     fos_user_security_login

            remember_me:
                secret:   %secret% 


        


    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        - { path: ^/admin, roles: ROLE_ADMIN }