<?php

namespace GM\GameBundle\Repository;

/**
 * GameRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;
use Doctrine\ORM\Tools\Pagination\Paginator;


class GameRepository extends \Doctrine\ORM\EntityRepository
{

    public function myFindAll()
    {
   
        
        $query = $this->createQueryBuilder('a')
        ->leftJoin('a.image', 'i')
        ->leftjoin('a.categories', 'c')
        ->leftjoin('a.platforms', 'p')
        ->addSelect('c')
        ->addSelect('p')
        ->addSelect('i')
        ->getQuery();

        $results = $query->getResult();

       
        return $results;
    }

    public function finByID($id)
    {
   
        
        $query = $this->createQueryBuilder('a')
        ->leftJoin('a.image', 'i')
        ->leftjoin('a.categories', 'c')
        ->leftjoin('a.platforms', 'p')
        ->addSelect('c')
        ->addSelect('p')
        ->addSelect('i')
        ->where('a.id = :gid')
        ->setParameter('gid', $id) 
        ->getQuery();

        $results = $query->getResult();

       
        return $results;
    }


    

}
