<?php

namespace GM\GameBundle\Repository;

/**
 * platformRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlatformRepository extends \Doctrine\ORM\EntityRepository
{
}
