<?php

namespace GM\UserBundle\Repository;

/**
 * ImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserImageRepository extends \Doctrine\ORM\EntityRepository
{
}
